# Generated by Django 5.2.5 on 2025-08-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('partner_organization', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=100)),
                ('capabilities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capabilities', models.TextField()),
                ('description', models.TextField()),
                ('inventory_code', models.CharField(max_length=100, unique=True)),
                ('usage_domain', models.CharField(max_length=100)),
                ('support_phase', models.CharField(max_length=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='cap.facility')),
            ],
        ),
    ]
