# Generated by Django 5.2.5 on 2025-09-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('affiliation', models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('Eng', 'Engineering'), ('Other', 'Other')], max_length=50)),
                ('specialization', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Business', 'Business')], max_length=50)),
                ('cross_skill_trained', models.BooleanField(default=False)),
                ('institution', models.CharField(choices=[('SCIT', 'SCIT'), ('CEDAT', 'CEDAT'), ('UniPod', 'UniPod'), ('UIRI', 'UIRI'), ('Lwera', 'Lwera')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_project', models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Contributor', 'Contributor')], max_length=50)),
                ('skill_role', models.CharField(choices=[('Developer', 'Developer'), ('Engineer', 'Engineer'), ('Designer', 'Designer'), ('Business Lead', 'Business Lead')], max_length=50)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to='participants.participant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='projects.project')),
            ],
        ),
    ]
