# Generated by Django 5.2.5 on 2025-09-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('partner_organization', models.CharField(blank=True, max_length=200)),
                ('facility_type', models.CharField(choices=[('Lab', 'Lab'), ('Workshop', 'Workshop'), ('Testing Center', 'Testing Center')], default='Lab', max_length=50)),
                ('capabilities', models.CharField(choices=[('CNC', 'CNC'), ('PCB Fabrication', 'PCB Fabrication'), ('Materials Testing', 'Materials Testing')], default='CNC', max_length=50)),
            ],
        ),
    ]
