# Generated by Django 5.2.5 on 2025-09-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Machining', 'Machining'), ('Training', 'Training'), ('Testing', 'Testing')], default='General', max_length=100)),
                ('skill_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Integration', 'Integration')], default='Hardware', max_length=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
            ],
        ),
    ]
