# Generated by Django 5.2.5 on 2025-09-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('nature_of_project', models.CharField(choices=[('research', 'Research'), ('prototype', 'Prototype'), ('applied', 'Applied Work')], default='research', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('innovation_focus', models.CharField(blank=True, max_length=255)),
                ('prototype_stage', models.CharField(choices=[('concept', 'Concept'), ('prototype', 'Prototype'), ('mvp', 'MVP'), ('market_launch', 'Market Launch')], default='concept', max_length=20)),
                ('testing_requirements', models.TextField(blank=True)),
                ('commercialization_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='facilities.facility')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='programs.program')),
            ],
        ),
    ]
