# Generated by Django 5.2.5 on 2025-09-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('artifact_link', models.URLField(blank=True)),
                ('outcome_type', models.CharField(choices=[('cad', 'CAD'), ('pcb', 'PCB'), ('prototype', 'Prototype'), ('report', 'Report'), ('business_plan', 'Business Plan')], max_length=30)),
                ('quality_certification', models.CharField(blank=True, max_length=255)),
                ('commercialization_status', models.CharField(blank=True, choices=[('demoed', 'Demoed'), ('market_linked', 'Market Linked'), ('launched', 'Launched')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='projects.project')),
            ],
        ),
    ]
