# Generated by Django 5.2.5 on 2025-09-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capabilities', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('inventory_code', models.CharField(max_length=100, unique=True)),
                ('usage_domain', models.CharField(choices=[('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('IoT', 'IoT'), ('Other', 'Other')], default='Other', max_length=50)),
                ('support_phase', models.CharField(choices=[('Training', 'Training'), ('Prototyping', 'Prototyping'), ('Testing', 'Testing'), ('Commercialization', 'Commercialization')], default='Training', max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='facilities.facility')),
            ],
        ),
    ]
